include ../common.mk

all: \
	acronym.wasm \
	all-your-base.wasm \
	armstrong-numbers.wasm \
	bank-account.wasm \
	binary-search.wasm \
	circular-buffer.wasm \
	collatz-conjecture.wasm \
	darts.wasm \
	difference-of-squares.wasm \
	grains.wasm \
	hamming.wasm \
	hello_world.wasm \
	leap.wasm \
	nucleotide-count.wasm \
	pangram.wasm \
	raindrops.wasm \
	resistor-color.wasm \
	reverse-string.wasm \
	rna-transcription.wasm \
	triangle.wasm \
	two-fer.wasm

.PHONY: clean
clean:
	rm *.wasm